apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-cm
  namespace: staging
data:
  PORT: "3001"
  LOG_LEVEL: "info"
  OTEL_COLLECTOR_URL: "http://otel-collector:4318"
  OTEL_SERVICE_NAME: "user-service"
