kube-prometheus-stack:
  grafana:
    adminPassword: ""
alertmanagerConfig:
  smtp:   # remplir avec les credentials SMTP de votre compte Brevo
    host: "smtp-relay.brevo.com:587"
    from: ""   # doit etre l'adresse verifiee de votre compte Brevo
    username: "<smtp-username-brevo>"
    password: "<smtp-password-brevo>"
    to: ""
